/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.semanticadaptation.ui.tests;

import com.google.inject.Injector;
import fr.irisa.diverse.semanticadaptation.ui.internal.SemanticadaptationActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SemAdaptUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SemanticadaptationActivator.getInstance().getInjector("fr.irisa.diverse.semanticadaptation.SemAdapt");
	}

}
