/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.semanticadaptation.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SemAdaptAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/irisa/diverse/semanticadaptation/parser/antlr/internal/InternalSemAdapt.tokens");
	}
}
