/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.adaptivesemantics;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AdaptSemStandaloneSetup extends AdaptSemStandaloneSetupGenerated {

	public static void doSetup() {
		new AdaptSemStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
