/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.adaptivesemantics.ui;

import com.google.inject.Injector;
import fr.irisa.diverse.adaptivesemantics.ui.internal.AdaptivesemanticsActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AdaptSemExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(AdaptivesemanticsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		AdaptivesemanticsActivator activator = AdaptivesemanticsActivator.getInstance();
		return activator != null ? activator.getInjector(AdaptivesemanticsActivator.FR_IRISA_DIVERSE_ADAPTIVESEMANTICS_ADAPTSEM) : null;
	}

}
