/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.semanticadaptation.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SemAdaptUiModule extends AbstractSemAdaptUiModule {

	public SemAdaptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
