/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.semanticadaptation;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SemAdaptStandaloneSetup extends SemAdaptStandaloneSetupGenerated {

	public static void doSetup() {
		new SemAdaptStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
