/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.semanticadaptation.ui;

import com.google.inject.Injector;
import fr.irisa.diverse.semanticadaptation.ui.internal.SemanticadaptationActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SemAdaptExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SemanticadaptationActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SemanticadaptationActivator activator = SemanticadaptationActivator.getInstance();
		return activator != null ? activator.getInjector(SemanticadaptationActivator.FR_IRISA_DIVERSE_SEMANTICADAPTATION_SEMADAPT) : null;
	}

}
