/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.adaptivesemantics.ide;


/**
 * Use this class to register ide components.
 */
public class AdaptSemIdeModule extends AbstractAdaptSemIdeModule {
}
