/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.adaptivesemantics.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.irisa.diverse.adaptivesemantics.AdaptSemRuntimeModule;
import fr.irisa.diverse.adaptivesemantics.AdaptSemStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AdaptSemIdeSetup extends AdaptSemStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AdaptSemRuntimeModule(), new AdaptSemIdeModule()));
	}
	
}
