/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.semanticadaptation.serializer;

import com.google.inject.Inject;
import fr.irisa.diverse.semanticadaptation.services.SemAdaptGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class SemAdaptSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SemAdaptGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Rule_BindKeyword_6_0_q;
	protected AbstractElementAlias match_Rule_IOKeyword_7_0_q;
	protected AbstractElementAlias match_Rule_ResolveKeyword_5_0_q;
	protected AbstractElementAlias match_Rule_WhereKeyword_4_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SemAdaptGrammarAccess) access;
		match_Rule_BindKeyword_6_0_q = new TokenAlias(false, true, grammarAccess.getRuleAccess().getBindKeyword_6_0());
		match_Rule_IOKeyword_7_0_q = new TokenAlias(false, true, grammarAccess.getRuleAccess().getIOKeyword_7_0());
		match_Rule_ResolveKeyword_5_0_q = new TokenAlias(false, true, grammarAccess.getRuleAccess().getResolveKeyword_5_0());
		match_Rule_WhereKeyword_4_0_q = new TokenAlias(false, true, grammarAccess.getRuleAccess().getWhereKeyword_4_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Rule_BindKeyword_6_0_q.equals(syntax))
				emit_Rule_BindKeyword_6_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Rule_IOKeyword_7_0_q.equals(syntax))
				emit_Rule_IOKeyword_7_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Rule_ResolveKeyword_5_0_q.equals(syntax))
				emit_Rule_ResolveKeyword_5_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Rule_WhereKeyword_4_0_q.equals(syntax))
				emit_Rule_WhereKeyword_4_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'bind'?
	 *
	 * This ambiguous syntax occurs at:
	 *     conclusion=Conclusion 'where'? 'resolve'? (ambiguity) 'IO' inputs+=Input
	 *     conclusion=Conclusion 'where'? 'resolve'? (ambiguity) 'IO' outputs+=Output
	 *     conclusion=Conclusion 'where'? 'resolve'? (ambiguity) 'IO'? (rule end)
	 *     conditions+=Condition 'resolve'? (ambiguity) 'IO' inputs+=Input
	 *     conditions+=Condition 'resolve'? (ambiguity) 'IO' outputs+=Output
	 *     conditions+=Condition 'resolve'? (ambiguity) 'IO'? (rule end)
	 *     premises+=Premise (ambiguity) 'IO' inputs+=Input
	 *     premises+=Premise (ambiguity) 'IO' outputs+=Output
	 *     premises+=Premise (ambiguity) 'IO'? (rule end)
	 */
	protected void emit_Rule_BindKeyword_6_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'IO'?
	 *
	 * This ambiguous syntax occurs at:
	 *     bindings+=Binding (ambiguity) (rule end)
	 *     conclusion=Conclusion 'where'? 'resolve'? 'bind'? (ambiguity) (rule end)
	 *     conditions+=Condition 'resolve'? 'bind'? (ambiguity) (rule end)
	 *     premises+=Premise 'bind'? (ambiguity) (rule end)
	 */
	protected void emit_Rule_IOKeyword_7_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'resolve'?
	 *
	 * This ambiguous syntax occurs at:
	 *     conclusion=Conclusion 'where'? (ambiguity) 'bind' bindings+=Binding
	 *     conclusion=Conclusion 'where'? (ambiguity) 'bind'? 'IO' inputs+=Input
	 *     conclusion=Conclusion 'where'? (ambiguity) 'bind'? 'IO' outputs+=Output
	 *     conclusion=Conclusion 'where'? (ambiguity) 'bind'? 'IO'? (rule end)
	 *     conditions+=Condition (ambiguity) 'bind' bindings+=Binding
	 *     conditions+=Condition (ambiguity) 'bind'? 'IO' inputs+=Input
	 *     conditions+=Condition (ambiguity) 'bind'? 'IO' outputs+=Output
	 *     conditions+=Condition (ambiguity) 'bind'? 'IO'? (rule end)
	 */
	protected void emit_Rule_ResolveKeyword_5_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'where'?
	 *
	 * This ambiguous syntax occurs at:
	 *     conclusion=Conclusion (ambiguity) 'resolve' premises+=Premise
	 *     conclusion=Conclusion (ambiguity) 'resolve'? 'bind' bindings+=Binding
	 *     conclusion=Conclusion (ambiguity) 'resolve'? 'bind'? 'IO' inputs+=Input
	 *     conclusion=Conclusion (ambiguity) 'resolve'? 'bind'? 'IO' outputs+=Output
	 *     conclusion=Conclusion (ambiguity) 'resolve'? 'bind'? 'IO'? (rule end)
	 */
	protected void emit_Rule_WhereKeyword_4_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
