/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.adaptivesemantics.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AdaptSemAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/irisa/diverse/adaptivesemantics/parser/antlr/internal/InternalAdaptSem.tokens");
	}
}
