/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.semanticadaptation.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.irisa.diverse.semanticadaptation.SemAdaptRuntimeModule;
import fr.irisa.diverse.semanticadaptation.SemAdaptStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SemAdaptIdeSetup extends SemAdaptStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SemAdaptRuntimeModule(), new SemAdaptIdeModule()));
	}
	
}
