/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.semanticadaptation.ide;


/**
 * Use this class to register ide components.
 */
public class SemAdaptIdeModule extends AbstractSemAdaptIdeModule {
}
