/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.adaptivesemantics.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAdaptSemScopeProvider extends DelegatingScopeProvider {
}
