/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.adaptivesemantics.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AdaptSemUiModule extends AbstractAdaptSemUiModule {

	public AdaptSemUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
