/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.semanticadaptation.scoping;

import fr.irisa.diverse.adaptivesemantics.scoping.AdaptSemScopeProvider;

public abstract class AbstractSemAdaptScopeProvider extends AdaptSemScopeProvider {
}
