/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.adaptivesemantics.serializer;

import com.google.inject.Inject;
import fr.irisa.diverse.adaptivesemantics.services.AdaptSemGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class AdaptSemSyntacticSequencer extends AbstractSyntacticSequencer {

	protected AdaptSemGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Primary_LeftParenthesisKeyword_0_0_a;
	protected AbstractElementAlias match_Primary_LeftParenthesisKeyword_0_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (AdaptSemGrammarAccess) access;
		match_Primary_LeftParenthesisKeyword_0_0_a = new TokenAlias(true, true, grammarAccess.getPrimaryAccess().getLeftParenthesisKeyword_0_0());
		match_Primary_LeftParenthesisKeyword_0_0_p = new TokenAlias(true, false, grammarAccess.getPrimaryAccess().getLeftParenthesisKeyword_0_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Primary_LeftParenthesisKeyword_0_0_a.equals(syntax))
				emit_Primary_LeftParenthesisKeyword_0_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Primary_LeftParenthesisKeyword_0_0_p.equals(syntax))
				emit_Primary_LeftParenthesisKeyword_0_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '!' expr=Primary
	 *     (rule start) (ambiguity) '-' expr=Primary
	 *     (rule start) (ambiguity) 'self' (rule start)
	 *     (rule start) (ambiguity) def=[SymbolDef|ID]
	 *     (rule start) (ambiguity) reciever=TerminalAccessExpression
	 *     (rule start) (ambiguity) value=BOOL
	 *     (rule start) (ambiguity) value=DOUBLE
	 *     (rule start) (ambiguity) value=INT
	 *     (rule start) (ambiguity) value=STRING
	 *     (rule start) (ambiguity) {And.lhs=}
	 *     (rule start) (ambiguity) {Div.lhs=}
	 *     (rule start) (ambiguity) {Equal.lhs=}
	 *     (rule start) (ambiguity) {Less.lhs=}
	 *     (rule start) (ambiguity) {LessEq.lhs=}
	 *     (rule start) (ambiguity) {Minus.lhs=}
	 *     (rule start) (ambiguity) {Mult.lhs=}
	 *     (rule start) (ambiguity) {NotEqual.lhs=}
	 *     (rule start) (ambiguity) {Or.lhs=}
	 *     (rule start) (ambiguity) {Plus.lhs=}
	 *     (rule start) (ambiguity) {SemanticDomainAccess.reciever=}
	 */
	protected void emit_Primary_LeftParenthesisKeyword_0_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) {And.lhs=}
	 *     (rule start) (ambiguity) {Div.lhs=}
	 *     (rule start) (ambiguity) {Equal.lhs=}
	 *     (rule start) (ambiguity) {Less.lhs=}
	 *     (rule start) (ambiguity) {LessEq.lhs=}
	 *     (rule start) (ambiguity) {Minus.lhs=}
	 *     (rule start) (ambiguity) {Mult.lhs=}
	 *     (rule start) (ambiguity) {NotEqual.lhs=}
	 *     (rule start) (ambiguity) {Or.lhs=}
	 *     (rule start) (ambiguity) {Plus.lhs=}
	 */
	protected void emit_Primary_LeftParenthesisKeyword_0_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
