/**
 * generated by Xtext 2.25.0
 */
package fr.irisa.diverse.semanticadaptation.generator;

import com.google.common.collect.Iterators;
import fr.irisa.diverse.adaptivesemantics.generator.AdaptationProcessGenerator;
import fr.irisa.diverse.adaptivesemantics.generator.NamingUtils;
import fr.irisa.diverse.adaptivesemantics.generator.RuleUtils;
import fr.irisa.diverse.adaptivesemantics.generator.visitors.PatternCheckerCompiler;
import fr.irisa.diverse.adaptivesemantics.generator.visitors.RuleCompiler;
import fr.irisa.diverse.adaptivesemantics.generator.visitors.SymbolPath;
import fr.irisa.diverse.adaptivesemantics.generator.visitors.SymbolResolver;
import fr.irisa.diverse.adaptivesemantics.model.adaptivesemantics.CondExpr;
import fr.irisa.diverse.adaptivesemantics.model.adaptivesemantics.Condition;
import fr.irisa.diverse.adaptivesemantics.model.adaptivesemantics.Expr;
import fr.irisa.diverse.adaptivesemantics.model.adaptivesemantics.Model;
import fr.irisa.diverse.adaptivesemantics.model.adaptivesemantics.Rule;
import fr.irisa.diverse.adaptivesemantics.model.adaptivesemantics.SymbolDef;
import fr.irisa.diverse.adaptivesemantics.model.adaptivesemantics.TermDef;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.eclipse.xtext.xbase.lib.ListExtensions;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import semanticadaptation.Adaptation;
import semanticadaptation.After;
import semanticadaptation.Before;
import semanticadaptation.Pointcut;
import semanticadaptation.Specialization;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class SemAdaptGenerator extends AbstractGenerator {
  private Map<Rule, Map<SymbolDef, SymbolPath>> symbolTable = CollectionLiterals.<Rule, Map<SymbolDef, SymbolPath>>newHashMap();
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    Model _head = IteratorExtensions.<Model>head(Iterators.<Model>filter(resource.getAllContents(), Model.class));
    final Model metamodel = ((Model) _head);
    RuleUtils.setSemanticdomain(metamodel.getSemanticdomain());
    RuleUtils.setModelName(NamingUtils.nameOf(metamodel));
    final boolean isLangGenerated = fsa.isFile(NamingUtils.processPathFor(RuleUtils.getModelName(), NamingUtils.LanguageName()));
    final boolean isContextGenerated = fsa.isFile(NamingUtils.processPathFor(RuleUtils.getModelName(), NamingUtils.LanguageName()));
    final boolean isLoopGenerated = fsa.isFile(NamingUtils.processPathFor(RuleUtils.getModelName(), NamingUtils.LanguageName()));
    if ((!isLangGenerated)) {
      fsa.generateFile(NamingUtils.processPathFor(RuleUtils.getModelName(), NamingUtils.LanguageName()), AdaptationProcessGenerator.language());
    }
    if ((!isContextGenerated)) {
      fsa.generateFile(NamingUtils.processPathFor(RuleUtils.getModelName(), NamingUtils.AdaptationContextName()), AdaptationProcessGenerator.adaptationcontext());
    }
    if ((!isLoopGenerated)) {
      fsa.generateFile(NamingUtils.processPathFor(RuleUtils.getModelName(), NamingUtils.FeedbackLoopName()), AdaptationProcessGenerator.feedbackloop());
    }
    final List<Adaptation> adaptations = IteratorExtensions.<Adaptation>toList(Iterators.<Adaptation>filter(resource.getAllContents(), Adaptation.class));
    final Function1<Adaptation, Rule> _function = (Adaptation adaptation) -> {
      return adaptation.getAdaptation();
    };
    final List<Rule> adaptationRules = ListExtensions.<Adaptation, Rule>map(adaptations, _function);
    this.createSymbolTableForRules(adaptationRules);
    final List<semanticadaptation.Module> modules = IteratorExtensions.<semanticadaptation.Module>toList(Iterators.<semanticadaptation.Module>filter(resource.getAllContents(), semanticadaptation.Module.class));
    for (final semanticadaptation.Module module : modules) {
      {
        final String moduleName = module.getName();
        final String moduleCode = this.compileModule(module, fsa);
        fsa.generateFile(NamingUtils.modulePathFor(RuleUtils.getModelName(), moduleName), moduleCode);
      }
    }
  }
  
  /**
   * Resolve symbols defined in rules to EMF model queries
   */
  public void createSymbolTableForRules(final List<Rule> rules) {
    for (final Rule rule : rules) {
      {
        final SymbolResolver resolver = new SymbolResolver();
        resolver.resolveFor(rule);
        final Map<SymbolDef, SymbolPath> ruleSymbols = resolver.getSymbolTable();
        this.symbolTable.put(rule, ruleSymbols);
      }
    }
  }
  
  public String compileModule(final semanticadaptation.Module module, final IFileSystemAccess2 fsa) {
    String matches = "";
    String addRules = "";
    String imports = "";
    EList<Adaptation> _adaptations = module.getAdaptations();
    for (final Adaptation adaptation : _adaptations) {
      {
        final String adaptationCode = this.compileAdaptationRule(adaptation.getAdaptation());
        fsa.generateFile(NamingUtils.adaptationPathFor(RuleUtils.getModelName(), adaptation.getAdaptation().getName()), adaptationCode);
        StringConcatenation _builder = new StringConcatenation();
        _builder.append(imports);
        _builder.newLineIfNotEmpty();
        _builder.append("import ");
        String _modelName = RuleUtils.getModelName();
        _builder.append(_modelName);
        _builder.append(".adaptations.rules.");
        String _adaptationNameFor = NamingUtils.adaptationNameFor(adaptation.getAdaptation().getName());
        _builder.append(_adaptationNameFor);
        _builder.append(";");
        _builder.newLineIfNotEmpty();
        imports = _builder.toString();
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.append(addRules);
        _builder_1.newLineIfNotEmpty();
        String _compileAdaptation = this.compileAdaptation(adaptation);
        _builder_1.append(_compileAdaptation);
        _builder_1.newLineIfNotEmpty();
        addRules = _builder_1.toString();
      }
    }
    int index = 0;
    EList<Pointcut> _pointcuts = module.getPointcuts();
    for (final Pointcut pointcut : _pointcuts) {
      {
        StringConcatenation _builder = new StringConcatenation();
        _builder.append(matches);
        _builder.newLineIfNotEmpty();
        String _compilePointcut = this.compilePointcut(pointcut, index);
        _builder.append(_compilePointcut);
        _builder.newLineIfNotEmpty();
        matches = _builder.toString();
        index++;
      }
    }
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package ");
    String _modelName = RuleUtils.getModelName();
    _builder.append(_modelName);
    _builder.append(".adaptations.modules;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import fr.diverse.team.SEALS.decision.model.Resource;");
    _builder.newLine();
    _builder.append("import fr.diverse.team.SEALS.decision.model.Softgoal;");
    _builder.newLine();
    _builder.append("import fr.diverse.team.SEALS.lang.semantics.AdaptableNode;");
    _builder.newLine();
    _builder.append("import fr.diverse.team.SEALS.module.adaptation.SelfAdaptationModule;");
    _builder.newLine();
    _builder.append("import ");
    String _modelName_1 = RuleUtils.getModelName();
    _builder.append(_modelName_1);
    _builder.append(".interpreter.");
    String _AdaptationContextName = NamingUtils.AdaptationContextName();
    _builder.append(_AdaptationContextName);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append(imports);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import ");
    String _modelName_2 = RuleUtils.getModelName();
    _builder.append(_modelName_2);
    _builder.append(".*;");
    _builder.newLineIfNotEmpty();
    _builder.append("import ");
    String _modelName_3 = RuleUtils.getModelName();
    _builder.append(_modelName_3);
    _builder.append(".interfaces.");
    String _interfaceNameFor = NamingUtils.interfaceNameFor(RuleUtils.getModelName());
    _builder.append(_interfaceNameFor);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public class ");
    String _moduleNameFor = NamingUtils.moduleNameFor(module.getName());
    _builder.append(_moduleNameFor);
    _builder.append(" extends SelfAdaptationModule<");
    String _AdaptationContextName_1 = NamingUtils.AdaptationContextName();
    _builder.append(_AdaptationContextName_1);
    _builder.append(", AdaptableNode<");
    String _interfaceNameFor_1 = NamingUtils.interfaceNameFor(RuleUtils.getModelName());
    _builder.append(_interfaceNameFor_1);
    _builder.append(">, ");
    String _interfaceNameFor_2 = NamingUtils.interfaceNameFor(RuleUtils.getModelName());
    _builder.append(_interfaceNameFor_2);
    _builder.append("> {");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ");
    String _moduleNameFor_1 = NamingUtils.moduleNameFor(module.getName());
    _builder.append(_moduleNameFor_1, "\t");
    _builder.append("() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("super(\"");
    String _name = module.getName();
    _builder.append(_name, "\t\t");
    _builder.append("\", null);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ");
    String _interfaceNameFor_3 = NamingUtils.interfaceNameFor(RuleUtils.getModelName());
    _builder.append(_interfaceNameFor_3, "\t");
    _builder.append(" adapt(");
    String _interfaceNameFor_4 = NamingUtils.interfaceNameFor(RuleUtils.getModelName());
    _builder.append(_interfaceNameFor_4, "\t");
    _builder.append(" configInterface) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append(addRules, "\t\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("return configInterface;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public boolean isTargetedNode(AdaptableNode<");
    String _interfaceNameFor_5 = NamingUtils.interfaceNameFor(RuleUtils.getModelName());
    _builder.append(_interfaceNameFor_5, "\t");
    _builder.append("> node) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append(matches, "\t\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void init(");
    String _AdaptationContextName_2 = NamingUtils.AdaptationContextName();
    _builder.append(_AdaptationContextName_2, "\t");
    _builder.append(" adaptationContext) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("// TODO Auto-generated method stub");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void connectSoftGoal(Softgoal softgoal) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// TODO Auto-generated method stub");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void connectResource(Resource resource) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// TODO Auto-generated method stub");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }
  
  protected String _compileAdaptation(final Specialization adaptation) {
    final String adaptationRuleName = NamingUtils.adaptationNameFor(adaptation.getAdaptation().getName());
    final String adaptedRuleName = adaptation.getTarget().getName();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("configInterface.add_specialize_");
    _builder.append(adaptedRuleName);
    _builder.append("(new ");
    _builder.append(adaptationRuleName);
    _builder.append("());");
    return _builder.toString();
  }
  
  protected String _compileAdaptation(final Before adaptation) {
    final String adaptationRuleName = NamingUtils.adaptationNameFor(adaptation.getAdaptation().getName());
    final String adaptedRuleName = adaptation.getTarget().getName();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("configInterface.add_before_");
    _builder.append(adaptedRuleName);
    _builder.append("(new ");
    _builder.append(adaptationRuleName);
    _builder.append("());");
    return _builder.toString();
  }
  
  protected String _compileAdaptation(final After adaptation) {
    final String adaptationRuleName = NamingUtils.adaptationNameFor(adaptation.getAdaptation().getName());
    final String adaptedRuleName = adaptation.getTarget().getName();
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("configInterface.add_after_");
    _builder.append(adaptedRuleName);
    _builder.append("(new ");
    _builder.append(adaptationRuleName);
    _builder.append("());");
    return _builder.toString();
  }
  
  public String compileAdaptationRule(final Rule rule) {
    final Map<SymbolDef, SymbolPath> ruleTable = this.symbolTable.get(rule);
    final RuleCompiler ruleCompiler = new RuleCompiler(ruleTable);
    final String effect = ruleCompiler.compileEffect(rule);
    StringConcatenation _builder = new StringConcatenation();
    _builder.append(effect);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("if(result != null){");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("if(! ((EObject) result).eClass().getEPackage().equals(");
    String _firstUpper = StringExtensions.toFirstUpper(RuleUtils.getSemanticdomain().getName());
    _builder.append(_firstUpper, "\t");
    _builder.append("Package.eINSTANCE)){");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("return ((Node) result).accept(vis, execCtx);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return result;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    final String core = _builder.toString();
    final String compiledRule = ruleCompiler.compileGuards(rule, core);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("package ");
    String _modelName = RuleUtils.getModelName();
    _builder_1.append(_modelName);
    _builder_1.append(".adaptations.rules;");
    _builder_1.newLineIfNotEmpty();
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.ecore.EObject;");
    _builder_1.newLine();
    _builder_1.append("import org.eclipse.emf.ecore.util.EcoreUtil;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import fr.diverse.team.SEALS.lang.semantics.AdaptableNode;");
    _builder_1.newLine();
    _builder_1.append("import fr.diverse.team.SEALS.lang.semantics.Node;");
    _builder_1.newLine();
    _builder_1.append("import fr.diverse.team.SEALS.lang.semantics.SelfAdaptiveVisitor;");
    _builder_1.newLine();
    _builder_1.append("import fr.diverse.team.SEALS.lang.semantics.SemanticsAdaptationInterface;");
    _builder_1.newLine();
    _builder_1.append("import ");
    String _modelName_1 = RuleUtils.getModelName();
    _builder_1.append(_modelName_1);
    _builder_1.append(".*;");
    _builder_1.newLineIfNotEmpty();
    _builder_1.append("import ");
    String _modelName_2 = RuleUtils.getModelName();
    _builder_1.append(_modelName_2);
    _builder_1.append(".ASOS.AdaptationRule;");
    _builder_1.newLineIfNotEmpty();
    _builder_1.append("import ");
    String _modelName_3 = RuleUtils.getModelName();
    _builder_1.append(_modelName_3);
    _builder_1.append(".ASOS.Termination;");
    _builder_1.newLineIfNotEmpty();
    _builder_1.append("import ");
    String _modelName_4 = RuleUtils.getModelName();
    _builder_1.append(_modelName_4);
    _builder_1.append(".");
    String _name = RuleUtils.getSemanticdomain().getName();
    _builder_1.append(_name);
    _builder_1.append(".*;");
    _builder_1.newLineIfNotEmpty();
    _builder_1.append("import ");
    String _modelName_5 = RuleUtils.getModelName();
    _builder_1.append(_modelName_5);
    _builder_1.append(".operations.data.");
    String _dataNameFor = NamingUtils.dataNameFor(rule.getConclusion().getFrom().getConcept().getName());
    _builder_1.append(_dataNameFor);
    _builder_1.append(";");
    _builder_1.newLineIfNotEmpty();
    _builder_1.newLine();
    _builder_1.append("public class ");
    String _adaptationNameFor = NamingUtils.adaptationNameFor(rule.getName());
    _builder_1.append(_adaptationNameFor);
    _builder_1.append(" extends AdaptationRule {");
    _builder_1.newLineIfNotEmpty();
    _builder_1.append("\t");
    _builder_1.append("@Override");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("public Object adapt(SelfAdaptiveVisitor vis, AdaptableNode<? extends SemanticsAdaptationInterface> adaptableNode, Object execCtx, SemanticsAdaptationInterface config){");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    String _name_1 = rule.getConclusion().getFrom().getConcept().getName();
    _builder_1.append(_name_1, "\t\t");
    _builder_1.append(" node = ((");
    String _name_2 = rule.getConclusion().getFrom().getConcept().getName();
    _builder_1.append(_name_2, "\t\t");
    _builder_1.append(") adaptableNode);");
    _builder_1.newLineIfNotEmpty();
    _builder_1.append("\t\t");
    String _dataNameFor_1 = NamingUtils.dataNameFor(rule.getConclusion().getFrom().getConcept().getName());
    _builder_1.append(_dataNameFor_1, "\t\t");
    _builder_1.append(" data = new ");
    String _dataNameFor_2 = NamingUtils.dataNameFor(rule.getConclusion().getFrom().getConcept().getName());
    _builder_1.append(_dataNameFor_2, "\t\t");
    _builder_1.append("(execCtx);");
    _builder_1.newLineIfNotEmpty();
    _builder_1.append("\t\t");
    _builder_1.append("Object result = null;");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.append(compiledRule, "\t\t");
    _builder_1.newLineIfNotEmpty();
    _builder_1.append("\t\t");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.append("return result;");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    return _builder_1.toString();
  }
  
  public String compilePointcut(final Pointcut pointcut, final int pointcutIndex) {
    String out = "return true;";
    boolean _isRecursive = pointcut.isRecursive();
    if (_isRecursive) {
    } else {
    }
    final SymbolResolver resolver = new SymbolResolver();
    final EClass concept = pointcut.getStructure().getConcept();
    final EList<EStructuralFeature> features = concept.getEAllStructuralFeatures();
    final EList<TermDef> childs = pointcut.getStructure().getChilds();
    final int len = childs.size();
    for (int i = 0; (i < len); i++) {
      {
        final TermDef child = childs.get(i);
        final SymbolPath sp = new SymbolPath("node", "", "");
        resolver.resolveFirst(child, features.get(i), sp);
      }
    }
    Map<SymbolDef, SymbolPath> _symbolTable = resolver.getSymbolTable();
    final RuleCompiler rulecompiler = new RuleCompiler(_symbolTable);
    List<Condition> _reverse = ListExtensions.<Condition>reverse(pointcut.getConditions());
    for (final Condition cond : _reverse) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("if(");
      CondExpr _cond = cond.getCond();
      String _compile = rulecompiler.compile(((Expr) _cond));
      _builder.append(_compile);
      _builder.append("){");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.append(out, "\t");
      _builder.newLineIfNotEmpty();
      _builder.append("}");
      _builder.newLine();
      out = _builder.toString();
    }
    final PatternCheckerCompiler patternCompiler = new PatternCheckerCompiler();
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("boolean match");
    _builder_1.append(pointcutIndex);
    _builder_1.append(" = true");
    String _compile_1 = patternCompiler.compile(pointcut.getStructure(), "node", "node", null);
    _builder_1.append(_compile_1);
    _builder_1.append(";");
    _builder_1.newLineIfNotEmpty();
    _builder_1.append("if(match");
    _builder_1.append(pointcutIndex);
    _builder_1.append("){");
    _builder_1.newLineIfNotEmpty();
    _builder_1.append("\t");
    _builder_1.append(out, "\t");
    _builder_1.newLineIfNotEmpty();
    _builder_1.append("}");
    _builder_1.newLine();
    out = _builder_1.toString();
    return out;
  }
  
  public String compileAdaptation(final Adaptation adaptation) {
    if (adaptation instanceof After) {
      return _compileAdaptation((After)adaptation);
    } else if (adaptation instanceof Before) {
      return _compileAdaptation((Before)adaptation);
    } else if (adaptation instanceof Specialization) {
      return _compileAdaptation((Specialization)adaptation);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(adaptation).toString());
    }
  }
}
